# Generated by Django 5.1.5 on 2025-02-22 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('employee_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Supervisor', 'Supervisor'), ('Executive', 'Executive')], default='Executive', max_length=20)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ccd_userlogin',
            },
        ),
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('unique_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('link_count', models.IntegerField(blank=True, null=True)),
                ('copyright_status', models.CharField(max_length=255)),
                ('link_status', models.CharField(max_length=255)),
                ('processed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ccd_discovery',
            },
        ),
        migrations.CreateModel(
            name='DomainReview',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('link_status', models.CharField(max_length=255)),
                ('content_status', models.CharField(max_length=255)),
                ('invalid_reason', models.CharField(max_length=255, null=True)),
                ('content_type', models.CharField(max_length=255)),
                ('proceed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccd_app.discovery', to_field='url', unique=True)),
            ],
            options={
                'db_table': 'ccd_domainreview',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('download_status', models.CharField(max_length=100)),
                ('path_link', models.CharField(blank=True, max_length=255, null=True)),
                ('reason_for_notdownloaded', models.TextField(blank=True, null=True)),
                ('downloadprocessed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccd_app.domainreview', to_field='url', unique=True)),
            ],
            options={
                'db_table': 'ccd_download',
            },
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('unique_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cleaning_status', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('link_count', models.IntegerField(blank=True, null=True)),
                ('link_status', models.CharField(max_length=255)),
                ('content_status', models.CharField(max_length=255)),
                ('download_status', models.CharField(blank=True, max_length=100, null=True)),
                ('path_Link', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('advertisment_level', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright_status', models.CharField(blank=True, max_length=255, null=True)),
                ('crawl_method', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('webpage_url_id', models.ForeignKey(blank=True, db_column='webpage_url_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='ccd_app.domainreview', to_field='url')),
                ('download_url_id', models.ForeignKey(blank=True, db_column='download_url_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='ccd_app.download', to_field='url_id')),
            ],
            options={
                'db_table': 'ccd_cleaning',
            },
        ),
    ]
