from django.urls import path
from .views import LoginView,submit_discovery
from . import views

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('usercreation/', views.user_creation, name='usercreation'),
    path('workallocation/', views.work_allocation, name='workallocation'), 
    path('dashboard/', views.dashboard, name='dashboard'),
    #path('supervisor-only/', views.supervisor_only, name='supervisor_only'),
    path('discovery/', views.discovery_view, name='discovery'),
    path('domain-review/', views.domain_review_view, name='domain_review'),
    path('download/', views.download, name='download'),
    path('cleaning/', views.cleaning_view, name='cleaning'),
    path('reports/', views.reports, name='reports'),
    #path('employee-selector/', views.employee_selector, name='employee_selector'),
    path('submit-discovery/', submit_discovery, name='submit_discovery'), 
    path('check-keyword/', views.check_keyword, name='check_keyword'),
    path('check-url/', views.check_url, name='check_url'),
    path('ccd/domaincheck-url/', views.check_domain_url, name='check_domain_url'),
    path('fetch-next-unsubmitted-url/', views.fetch_next_unsubmitted_url, name='fetch_next_unsubmitted_url'),
    path('submit_domainreview/', views.submit_domainreview, name='submit_domainreview'),
    path('check_domainurl/', views.check_domainurl, name='check_domainurl'),
    path('submit_download/', views.submit_download, name='submit_download'),
    path('fetch-next-url/', views.fetch_next_url, name='fetch_next_url'),
    path('check_downloadurl/', views.check_downloadurl, name='check_downloadurl'),
    path('fetch-url-details', views.fetch_url_details, name='fetch_url_details'),
    path('check_cleaningurl/', views.check_cleaningurlWebpage, name='check_cleaningurlWebpage'),
    path('check_downloadCleaningUrl/', views.check_downloadCleaningUrl, name='check_downloadCleaningUrl'),
    path('fetch-next-webpage-url/', views.fetch_next_webpage_url, name='fetch_next_webpage_url'),
    path('fetch-next-downloaded-url/', views.fetch_next_downloaded_url, name='fetch_next_downloaded_url'),
    path('submit_cleaning/', views.submit_cleaning, name='submit_cleaning'),
    path('submit_report/', views.submit_report, name='submit_report'),
    path('get_work_allocations/', views.get_work_allocations, name='get_work_allocations'),
    path('generate_report/',views.generate_report,name ='generate_report'),
    path('all_users/', views.get_all_users, name='all_users'),
    path('work_allocations/', views.get_work_allocations, name='get_work_allocations'),
    path('downloadGeneratedReport/',views.downloadGeneratedReport,name ='downloadGeneratedReport'),
    path('logout/', views.logout_view, name='logout'),
]
